### ISSUE TITLE
[Q] oracle in the jvm?

### ISSUE THREAD

**Issue by Lanchon** [CalebFenton/dex-oracle#11]
hi,

i admit to be very lazy and haven't tried this tool.

before i found it i was thinking of writing a similar tool but with a couple of differences:

a) processing dex using dexlib2 instead of processing smali text.
b) running target code in the jvm itself.

instead of a device or emulator, i thought of simply running the dex through dex2jar and invoking methods directly.

to sandbox, i thought of implementing a class loader that breaks the common pattern of delegation and only delegate classes that are whitelisted as safe (eg: String). classes that are loadable in the parent class loader but are not whitelisted would throw an error. and the rest would be loaded from the dex2jar jar.

i thought of mentioning this because you might think that this is an improvement over the current implementation, or at least a welcomed option. for literal decryption, i guess there wouldn't be to much whitelisting needed. in any case, an automated whitelisting solution could be developed.

i never implemented a class loader sandbox so my ideas could be way off. i just imagine how the JVM works, i haven't read much.

the sharing of whitelisted classes between contexts could be a problem. eg, a java.lang class could have static fields that get modified by the target code and end up influencing dex-oracle. an alternative would be not to delegate anything and load new class copies from the java runtime jar in the target class loader.

for instance, String could be loaded again, this time by the oracle class loader. passing a string argument to target code would entail building an oracle String using reflection from main code, since system String is not the same class as oracle String. Object and arrays at least would need to be treated specially. with this solution there might not be a need to whitelist anything: if access to native methods is forbidden, the whole java runtime would be neutered. in fact, the android runtime could be used instead (minus native implementations, obviously).

actually a mix of both strategies would work too, whitelisting String, Integer, et al from the system class loader to avoid marshaling to/from oracle, and reloading other runtime classes

**Comment by CalebFenton** [comment]
Hey Lanchon, you seem busy lately!

Using a decompiler to create a jar and using reflection or class loading to execute stuff is cool, and I've used that technique several times. The problem is decompilers are pretty, uh "low fidelity" (read: terrible) and don't produce semantically equivalent or sometimes even valid bytecode. Baksmali isn't perfect, but it's much higher fidelity and Smali semantics are really simple and highly regular, unlike Java source code. Using dexlib objects directly, it seems like the rules you would need to write would be more complicated and harder for people to understand.

You're absolutely going to need to provide the Android runtime if you want most code to work, or at least the stubs. Lots of important code are in activities, services and other components, and those would fail to load without the runtime.

If you're going to hardcore sandbox the class loader, you should know that you're not allowed to load "java.lang" classes without bending over backwards and running your code using special agents and other stuff that I never really figured out. It makes sense from a security standpoint, but I was bitten by it when I tried to completely control the class loader for Simplify's dynamic class generation.

I actually tried to build something similar to what you described at first before deciding to just run the original dex file on a real Android system and target Smali rather than something more high level. Running on Android also makes it easier to add support for native libs.

**Comment by Lanchon** [comment]
lol, i'm very aware of the problems with java decompilers, that's why i wrote this toolset that i've been using very effectively:
http://forum.xda-developers.com/android/software/tool-dexpatcher-modify-android-dex-apk-t3060854

but i wouldn't say decompilers are terrible. it's just a very difficult task, sometimes impossible even: some valid verifiable bytecode simply cannot be expressed in java.

[the solution to this conundrum is obvious, btw: someone has to design a javaesque language that can express all bytecode and create translators for both directions and that's it. kind of a high level smali/jasmin that could be a superset of java but probably shouldn't be. but this is off-topic here...]

i never mentioned decompilers, i said dex2jar which does a very good job. before writing dexpatcher i used to rip out proprietary service client libraries from dex files, dex2jar them, include them in android or java projects, and do dirty deeds with them. dedexed dex executes just fine, never had a problem. though i admit i only tired with non-obfuscated and proguarded dex code, never with code gone through dexguard et al.

> You're absolutely going to need...
i said i was thinking of writing something like this before i found your tool. i am definitely not writing one now that dex-oracle exists! :)

> You're absolutely going to need to provide the Android runtime if you want most code to work...
i just want the decrypt functions to work. but yes, <clinit> methods may requite much more than basic java.lang. this is a real problem, i concur.

> you should know that you're not allowed to load "java.lang" classes...
yes, i know, read your death and classloaders post. i never knew before. not an issue i think. dex2jar can remap classes in jars, so worst case add one step after dedexing to remap java.lang classes to upyoursjava.lang (and of course the framework classes too). but there is no need to do this, the whitelist or a security manager could be enough.

anyway it was just an idea, i suppose an android emulator is good enough.
