### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by m-emelchenkov** [CalebFenton/dex-oracle#12]
(RuntimeError).gem/ruby/2.0.0/gems/dex-oracle-1.0.5/lib/dex-oracle/driver.rb:212:in `validate_output': app_process execution failure, output: 'Killed 
0'

Android 4.4.2/Arm emu

**Comment by m-emelchenkov** [comment]
Restricting to some path with "-i" solves the problem. It's good to include more human-readable error than "Killed 0".

**Comment by CalebFenton** [comment]
Do you have a hash of the apk?

Do you want to fix the error message :D

**Comment by m-emelchenkov** [comment]
Hash of apk? Why? Anyway, it's a private apk so I can't share.

Fix — no :-D. Because this tool proved useless for me—it does not restore original source from obfuscated code, absolutely no changes between obfuscated code and code passed to this tool, I dig into code manually with a certain success.

**Comment by CalebFenton** [comment]
Lol ok bro thanks for nothing.

**Comment by m-emelchenkov** [comment]
I do not thing that "nothing"—at least you should include this in Readme, as a "known issue". Or, now people can search in closed issues and solve the same problem.

**Comment by CalebFenton** [comment]
The issue is that app_process, a binary on your android environment, failed to execute some code. There are _literally_ an enumerable number of possible reasons for this, most of them center around the code threw an exception when executed. The error "Killed 0" is from app_process, and since this is an advanced tool and there are so many things that can go wrong, I decided to give the raw, unprocessed information for easier debugging.

I don't think this issue is going to be useful to anyone. I'll break it down for you. You've taken a tool which is meant to be a flexible aid rather than a point and click win button, ran it blindly against your apk without understanding it's limitations, and when it failed because, surprise, shit is complicated, you make an issue without giving enough detail to repro and without even giving the Android logs which would at least give me something to work with. Then, you low-key poo-poo the project and tell me to add your vague and useless report (read: complaint) to the readme as known issue.

**Comment by m-emelchenkov** [comment]
Sorry, I did not want to offend you.
