### ISSUE TITLE
Programm don't work

### ISSUE THREAD

**Issue by maxben14** [CalebFenton/dex-oracle#15]
I try deobfuscated cod in android apk on real device connected with usb. I use kali linux x86. But i don't understand why i get permission denied in log. Device with root.

My log:
root@kali:~# dex-oracle -i ru/my/test/Protected_App  /root/12.apk
failed to copy '/tmp/oracle-driver20170329-32112-13naw8n.zip' to '/data/local/od.zip': Permission denied
Optimizing 50 methods over 4612 Smali files.
failed to copy '/tmp/oracle-targets20170329-32112-ipstx8.json' to '/data/local/od-targets.json': Permission denied
/var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/dex-oracle/driver.rb:212:in `validate_output': a (RuntimeError)ution failure, output: 'Aborted 
0'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/dex-oracle/driver.rb:222:in `drive'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/dex-oracle/driver.rb:113:in `run_batch'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/dex-oracle/plugin.rb:47:in `apply_batch'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/dex-oracle/plugins/string_decryptor.rb:38:in `process'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/oracle.rb:33:in `block (2 levels) in process_plugins'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/oracle.rb:31:in `each'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/oracle.rb:31:in `block in process_plugins'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/oracle.rb:29:in `loop'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/oracle.rb:29:in `process_plugins'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/lib/oracle.rb:18:in `divine'
	from /var/lib/gems/2.3.0/gems/dex-oracle-1.0.5/bin/dex-oracle:94:in `<top (required)>'
	from /usr/local/bin/dex-oracle:23:in `load'
	from /usr/local/bin/dex-oracle:23:in `<main>'
Please, help me.

**Comment by CalebFenton** [comment]
The main issue seems to be that dex-oracle doesn't notice that /data/local isn't writable. Could you do `adb shell ls -l /data/local`?

As a work-around, you could also try running `adb root` to restart the adb daemon as root. This requires your device be rooted, but if it's an emulator (recommended) this should work.

**Comment by maxben14** [comment]
root@kali:~# adb root
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
adbd cannot run as root in production builds

root@kali:~# adb shell ls -l /data/local
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
opendir failed, Permission denied
root@kali:~# adb shell
shell@vee7e:/ $ cd /data
shell@vee7e:/data $ cd local
shell@vee7e:/data/local $ ls
opendir failed, Permission denied
255|shell@vee7e:/data/local $ su
root@vee7e:/data/local # ls -l
drwxrwx--x shell    shell             2017-03-22 00:28 tmp

I change right on 777 and working. But optimizing 0 methods.
Why 0 ? In my apk there are obfuscated code for example encode string and reflecsion classes.
I can send my apk your for research.
root@kali:~# dex-oracle -i ru/my/test/Protected_App /root/12.apk
3547 KB/s (2164386 bytes in 0.595s)
Optimizing 0 methods over 4612 Smali files.
Optimizations: 
Time elapsed 33.067681997 seconds

**Comment by CalebFenton** [comment]
It's optimizing 0 methods because it only looks for certain kinds of obfuscation patterns. This tool isn't a turn key solution for deobfuscation in general. It gives a framework for adding your own plugins and gives some default plugins I found useful. Unfortunately, deobfuscation in general case is difficult because once you have a solution that covers all cases, there's strong incentive to create a new problem not solved by the existing solution. It's an arms race.

You have at least two good options here.

First, understand how dex-oracle works. It searches for patterns in the smali, and then once it recognizes a pattern, it tries to simplify it. One way of simplifying is by rearranging the code in an easier to read form. This isn't very "penetrating" because you can only work with the limited information there. The "secret sauce" of dex-oracle is that it gives you an easy way to slice up parts of a program and execute them, thereby knowing exactly what they do. In other words, it uses limited execute to determine semantics. Once you get that, you have much more freedom to craft easier to read code. For example, replacing encrypted strings and calls to the decryption method, with simply the decrypted string. There's a plugin that searches for general patterns in this, but many obfuscators are a little more complex.

Second, try [Simplify](https://github.com/CalebFenton/simplify). It uses virtual execution (i.e. a somewhat imperfect VM) to determine semantics so it's a lot better in theory than Oracle. It'll probably work in some cases but not all (without some bug fixing). Also, there's the possibility what you're looking at isn't intentionally obfuscation.

**Comment by maxben14** [comment]
I tried to simplify, but for how long this program should work, I started to simplify and it took 6 hours, but it still worked and often there were exceptions in the log, but it did not end.

**Comment by CalebFenton** [comment]
It's covered in the documentation. Good luck.

**Comment by maxben14** [comment]
I want to ask how compile dex-oracle if i will add plugin with my patern ? How build without "gem install dex-oracle" command ?

**Comment by CalebFenton** [comment]
You should be able to `bundle intall` and just run `bin/dex-oracle` locally. Be sure to read the Hacking section of the readme for more info on making plugins. Feel free to ask specific questions on how to make your plugin.
