### ISSUE TITLE
Logging injection

### ISSUE THREAD

**Issue by dazzleworth** [CalebFenton/dex-oracle#36]
I intend to inject logging statements into smali code like `invoke-static {v1}, LLogger;->printObject(Ljava/lang/Object;)V`

Will I be able to see executed logging statements on the console when I run dex-oracle command?

**Comment by CalebFenton** [comment]
Since the code is executed by a command line on the emulator, you should get stdouts. I think stdout and stderr are captured by dex-oracle and the only way to print it out is with verboase mode.

dex-oracle itself is REALLY simple. It's just a wrapper that makes it easier to adb push a dex file to an emulator and run it. Try just running it yourself.

Here's an example of how to run it yourself: https://calebfenton.github.io/2015/12/22/what-happens-when-a-dex-includes-a-framework-class/
